name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.11.3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformExecutionRole
        aws-region: ap-southeast-1

    - name: Terraform Init
      run: terraform init
      working-directory: .

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: .