name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.11.3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/TerraformExecutionRole
        aws-region: ${{ secrets.AWS_REGION }}  # Updated to use secret

    - name: Terraform Init
      run: terraform init -backend-config="bucket=seafile-${{ secrets.AWS_REGION }}-${{ secrets.BACKEND_BUCKET_SUFFIX }}" -backend-config="key=seafile-terraform/terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="dynamodb_table=${{ secrets.BACKEND_DYNAMODB_TABLE }}"
      working-directory: .

    - name: Terraform Destroy
      env:
        TF_VAR_admin_ui_password: ${{ secrets.ADMIN_UI_PASSWORD }}
        TF_VAR_admin_ui_username: ${{ secrets.ADMIN_UI_USERNAME }}
        TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_mysql_username: ${{ secrets.MYSQL_USERNAME }}
        TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
        TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
        TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}
      run: terraform destroy -auto-approve
      working-directory: .